# Generated by Django 6.0.4 on 2026-04-28 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertlog',
            name='alert_type',
            field=models.CharField(choices=[('LOW_STOCK', 'Low Stock'), ('EXPIRING_60', 'Expiring in 60 days'), ('EXPIRING_30', 'Expiring in 30 days'), ('EXPIRED', 'Expired'), ('TEST', 'Test SMS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alertlog',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.medicine'),
        ),
    ]
